---
title: "iternum2 R analyses"
output: html_notebook
---


```{r libraries, echo=FALSE}

library(lme4) # need for running lmer
library(tidyverse)
library(coda)
require(languageR)
library(lmerTest) #need this for lmer p values!!! Maybe it's not so important...
library(emmeans)
library(data.table)
library(ggplot2)
# install.packages('sjPlot')
library(sjPlot)


```

```{r get_data, echo=FALSE}

Rdf <- read_csv("../results/csv/iterated_number_group_data_regularity1.csv")
df <- Rdf[c('outcome','drawDuration','numStrokes','Regularity','gameID','trialNum','category','cardinality')]

```

```{r}
t.test(df[df$Regularity == "random", ]['drawDuration'], y = df[df$Regularity == "regular" ,]['drawDuration'],
       alternative = c("two.sided"),
       mu = 0, paired = FALSE, var.equal = FALSE,
       conf.level = 0.95)


t.test(df[df$Regularity == "random", ]['outcome'], y = df[df$Regularity == "regular" ,]['outcome'],
       alternative = c("greater"),
       mu = 0, paired = FALSE, var.equal = FALSE,
       conf.level = 0.95)

```


```{r}

model1 <- lmer(data=df,drawDuration ~ category * cardinality * Regularity * trialNum + (1+cardinality*category| gameID))

model2 <- lmer(data=df,drawDuration ~ category * cardinality + Regularity * trialNum + (1 | gameID))

model3 <- lmer(data=df,drawDuration ~ cardinality * Regularity * trialNum + (1 + cardinality| gameID))
model4 <- lm(data=df,drawDuration ~ Regularity * trialNum)

BIC(model2)
summary(model2)
```

