---
title: "Iternum Pre-Reg Analyses (1,2,3)"
output: html_notebook
---


```{r libraries, echo=FALSE}

library(lme4) # need for running lmer
library(tidyverse)
library(coda)
require(languageR)
library(lmerTest) #need this for lmer p values!!! Maybe it's not so important...
library(emmeans)
library(data.table)
library(ggplot2)
library(sjPlot)
library(modelbased)


```

```{r get_data, echo=FALSE}

# first read all the data we saved out from each notebook
df1 <- read_csv("../results/csv/iternum_data1.csv")
df1.1 <- read_csv("../results/csv/recogData.csv")
# edit the df1 dataframe
dud_games = c(#"6769-3ee1e797-2c5b-4441-8d67-5ccd1c6b9a73",    #number
             "8369-76e6f73d-922a-4aca-b98a-8c96026aa48a",    #number
             "1372-60cdfd55-28bb-411c-b777-c51eaadee7a9",    #shape
             "2949-1e579088-8493-4c07-873c-7bd6d00685e3",    #shape
             "7197-6d1f3fda-040a-455c-aef0-279ba9aef053",    #shape
             "9237-4cc76e85-9955-4cef-b03c-5c68f46321ca",    #shape
             "1947-29382ba4-5747-456d-ba8b-276812fc1fb3")    #shape
bad_games <- df1[ df1$gameID %in% dud_games, ]
df1 <- df1[ ! df1$gameID %in% dud_games, ]
df1$block <- floor((df1$trialNum - 1) / 8) + 1 # get block number from trial number
df1$ratio <- df1$numStrokes / df1$cardinality

# create a 'block' column for the recog df
df1.1$block <- floor((df1.1$orig_game_trial_num - 1) / 8) + 1 # get block number from trial number of original game
df1.1 <- df1.1[!is.na(df1.1$block),]

# and rename the columns of recog df for compactness's sake:
names(df1.1)[names(df1.1) == "recog_gameID"] <- "RgameID"
names(df1.1)[names(df1.1) == "orig_game_id"] <- "OgameID"
names(df1.1)[names(df1.1) == "rating_trial_num"] <- "Rtrial"
names(df1.1)[names(df1.1) == "orig_game_trial_num"] <- "Otrial"
names(df1.1)[names(df1.1) == "rate_condition"] <- "Rcond"
names(df1.1)[names(df1.1) == "orig_game_condition"] <- "Ocond"
names(df1.1)[names(df1.1) == "orig_sketch_animal"] <- "shape"
names(df1.1)[names(df1.1) == "orig_sketch_cardinality"] <- "cardinality"



df2 <- read_csv("../results/csv/iternum_data2_incl.csv") # iternum_data2_excl.csv or iternum_data2_incl.csv
df2$vRT <- df2$vRT / 1000

df3 <- read_csv("../results/csv/iternum_data3.csv") # iternum_data3.csv or iternum_data3_effort.csv
# slightly more cleaning to do
df3$PT <- df3$submitTime - df3$trialStartTime
df3$RT <- df3$clickedTime - df3$submitTime # this is less than 0 exactly once. Ignore it?
df3$tokenRatio <- df3$messageLength / df3$cardinality  # number of tokens (1-to-1)
df3$symbolRatio <- df3$symbolsSum / df3$cardinality   # summed symbols (additive)


```

```{r maximal_models}

# Study 1 ***************************************************************************

model1ink <- lmer(data=df1,
                   meanPixelIntensity ~ category * cardinality * Game_Condition * block 
                   + (1+cardinality*category| gameID))

model1stroke <- lmer(data=df1,
                   numStrokes ~ category * cardinality * Game_Condition * block 
                   + (1+cardinality*category| gameID))

model1time <- lmer(data=df1,
                   drawDuration ~ category * cardinality * Game_Condition * block 
                   + (1+cardinality*category| gameID))

model1acc <- glmer(data=df1,
                   outcome ~ category * cardinality * Game_Condition * block 
                   + (1+cardinality*category| gameID), family = 'binomial')

# Study 1.1 *************************************************************************

model1.1 <- glmer(data=df1.1,
                  correct ~ Ocond * Rcond + block
                  + (1  | workerID) + (1  | OgameID) + (1|cardinality) + (1|shape),
                  family = 'binomial')


# Study 2 ***************************************************************************

model2PT <- lmer(data=df2,
                   drawDuration ~ category * cardinality * Regularity * block 
                   + (1+cardinality*category| gameID))

model2RT <- lmer(data=df2,
                   vRT ~ category * cardinality * Regularity * block 
                   + (1+cardinality*category| gameID))

model2acc <- glmer(data=df2,
                   outcome ~ category * cardinality * Regularity * block 
                   + (1+cardinality*category| gameID), family = 'binomial')

model2stroke <- lmer(data=df2,
                   strokeRatio ~ category * cardinality * Regularity * block 
                   + (1+cardinality*category| gameID))

# Study 3 ***************************************************************************

model3PT <- lmer(data=df3,
                 PT ~ cardinality * trialNum +
                   (1+cardinality | gameID))

model3RT <- lmer(data=df3,
                 RT ~ cardinality * trialNum +
                   (1+cardinality | gameID))

model3token <- lmer(data=df3,
                 tokenRatio ~ cardinality * trialNum +
                   (1+cardinality | gameID))

model3acc <- glmer(data=df3,
                   correct ~ cardinality * trialNum +
                     (1 + cardinality | gameID), family = 'binomial')

```

```{r hewn_models}



m <- lmer(data=df1,
          ratio ~  cardinality  * Game_Condition + cardinality:Game_Condition +  
    block+ (1+cardinality| gameID))

estimate_means(m)




# models of vRT didn't converge, likely because of outliers that threw everything off
# so remove the outliers:
# https://stackoverflow.com/questions/4787332/how-to-remove-outliers-from-a-dataset
hist(df2$vRT[!df2$vRT %in% boxplot.stats(df2$vRT)$out], breaks=100)

# the trouble is, it's excluding more than it should (296 entries):
length(df2$vRT) - length(df2$vRT[!df2$vRT %in% boxplot.stats(df2$vRT)$out])

# so what we should do is only exclude the really ridiculous ones. Notice how some of the numbers are outrageously big, while most of the outliers are pretty normal (still long, but believable)
# here's the count of outliers larger than 200,000 seconds, divided by the total outlier count:
sum(boxplot.stats(df2$vRT)$out > 200000000) / length(boxplot.stats(df2$vRT)$out)

# so let's just exclude the super wild ones and plot those:
outrageous <- boxplot.stats(df2$vRT)$out[boxplot.stats(df2$vRT)$out > 200000000]
hist(df2$vRT[!df2$vRT %in% outrageous], breaks=100)

# now subset the whole dataframe for this one analysis
df2_culled <- df2[!df2$vRT %in% outrageous, ]

# now we can run the lmer() again:
model2RT_culled <- lmer(data=df2_culled,
                   vRT ~ category + cardinality * Regularity * block
                   + (1| gameID))
summary(model2RT_culled)
BIC(model2RT_culled)




model3token <- lmer(data=df3,
                 tokenRatio ~ cardinality * trialNum +
                   (1 | gameID))
summary(model3token)

model3acc <- glm(data=df3,
                   correct ~ cardinality * trialNum , family = 'binomial')

summary(model3acc)
BIC(model3acc)
```

```{r old_and_new}

test <- glmer(data=df3,
                   correct ~ cardinality * trialNum +
                     (1 | gameID), family = 'binomial')

durModel1 <- lmer(data=df1,
                   drawDuration ~ cardinality + category + Game_Condition + cardinality:Game_Condition + block
                   + (1+cardinality| gameID))

summary(durModel1)

fullStroke <- lmer(data=df1,
                   numStrokes ~
                     category * cardinality * Game_Condition * block 
                   + (1+cardinality*category| gameID))

oldStroke <- lmer(data = df1, numStrokes ~
               cardinality + category * Game_Condition + cardinality:Game_Condition + block 
               + (1 + cardinality | gameID))

summary(oldStroke)

anova(full,removeCat)


PTstudy2 <- lmer(data=df2,
                   drawDuration ~  Regularity * strategy * cardinality
                   + (1| gameID))
summary(PTstudy2)

```


``` {r exploreFunction}

plotParams = function(D,dv_name,col_names) {
  tempModel = lmer(data=D, dv_name 
  return(BIC())
}

df1$gameID
df1$trialNum

x = c('category','cardinality')
x[1]

lmer(as.double(df1['drawDuration']) ~ as.double(df1['category']) + (1| df1$gameID))

     df1['drawDuration'] ~ df1['category'] * df1['cardinality'] 
                   + (1+cardinality| gameID))
  
  
  
  
test <- glmer(data=df1.1,
                  correct ~ Ocond + Rcond + Ocond:block + Rcond:block + Ocond:Rcond:block
                  + (1  | workerID) + (1  | OgameID) + (1|cardinality) + (1|shape),
                  family = 'binomial')
summary(test)

```


